/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Listas.Equipos;
import Listas.Jugadores;
import Listas.Partidos;
import Nodos.NodoEquipo;
import Nodos.NodoJugador;
import Nodos.NodoPartidos;
import project2014.clsLlenar;
import project2014.clsLlenarCalendario;

/**
 *
 * @author familia
 */
public class frmEquipos extends javax.swing.JFrame {

    /**
     * Creates new form frmM
     */
    public frmEquipos() {
        initComponents();
        Equipos EquiposOrdenados = new Equipos();
        clsLlenar llena = new clsLlenar();
        llena.relleno(EquiposOrdenados);
        NodoEquipo rec = EquiposOrdenados.getRaiz();

        while (rec != null) {
            System.out.println(rec.getNombre());
            cbxEquipos.addItem(rec.getNombre());

            rec = rec.getSiguienteEquipo();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxEquipos = new javax.swing.JComboBox();
        btnVer = new javax.swing.JButton();
        tbPartidos = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJugadores = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPartidos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbxEquipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Equipos" }));
        cbxEquipos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEquiposItemStateChanged(evt);
            }
        });
        cbxEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEquiposActionPerformed(evt);
            }
        });

        btnVer.setText("VER");
        btnVer.setEnabled(false);
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });

        tbPartidos.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        txtJugadores.setColumns(20);
        txtJugadores.setRows(5);
        jScrollPane1.setViewportView(txtJugadores);

        tbPartidos.addTab("Jugadores", jScrollPane1);

        txtPartidos.setColumns(20);
        txtPartidos.setRows(5);
        jScrollPane2.setViewportView(txtPartidos);

        tbPartidos.addTab("Partidos", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnVer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(tbPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cbxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnVer)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEquiposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEquiposItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxEquiposItemStateChanged

    private void cbxEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEquiposActionPerformed
        // TODO add your handling code here:
        if (cbxEquipos.getSelectedIndex() != 0) {
            btnVer.setEnabled(true);
        } else {
            btnVer.setEnabled(false);
        }
    }//GEN-LAST:event_cbxEquiposActionPerformed

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked

        Partidos calendar = new Partidos();
        clsLlenarCalendario cal = new clsLlenarCalendario();
        cal.Llenarcalendario(calendar);
        
        NodoPartidos recP = calendar.getCalendario();
        String todosPartidos="";
        while (recP != null) {

            if ( cbxEquipos.getSelectedItem()==recP.getLocal()
                    ||cbxEquipos.getSelectedItem()==recP.getVisita()) {
                
                todosPartidos+="          "+recP.getLocal()+" "+recP.getGlocal()
                        +"-"+recP.getGvisita()+" "+recP.getVisita()+"\n"+
                        recP.getGolesL()+"             "+recP.getGolesV();
            }

            recP = recP.getSiguientePartido();
            
        }
        
        
        
        Equipos equi = new Equipos();
        clsLlenar llena = new clsLlenar();
        llena.relleno(equi);       
        
        NodoEquipo rec = equi.getRaiz();
        String todosJugadores = "";

        while (rec != null) {

            if (rec.getNombre() == cbxEquipos.getSelectedItem()) {
                
                NodoJugador recJ = rec.getJugadores();
               
                
                while (recJ != null) {
                    todosJugadores += (recJ.getNombre()+ "\n");
                    recJ = recJ.getSiguienteJugador();
                }
                
            }

            rec = rec.getSiguienteEquipo();
        }
        this.txtPartidos.setText(todosPartidos);
        this.txtJugadores.setText(todosJugadores);
    }//GEN-LAST:event_btnVerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox cbxEquipos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tbPartidos;
    private javax.swing.JTextArea txtJugadores;
    private javax.swing.JTextArea txtPartidos;
    // End of variables declaration//GEN-END:variables
}
