/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Listas.Equipos;
import Listas.Grupos;
import Nodos.NodoEquipoenGrupo;
import Nodos.NodoGrupo;
import project2014.clsLlenarGrupos;

/**
 *
 * @author Jose E & Alvaro
 */
public class frmGrupos extends javax.swing.JFrame {

    /**
     * Creates new form frmGrupos
     */
    private boolean estado;

    public frmGrupos() {
        initComponents();
        this.setSize(400, 430);
        Grupos rellenar = new Grupos();
        clsLlenarGrupos TodosG = new clsLlenarGrupos();
        TodosG.LlenarGrupo(rellenar);
        NodoGrupo recorridoG = rellenar.getGrupoX();

        String mensaje = "";
        while (recorridoG != null) {
            Equipos recE = recorridoG.getListaEquipos();
            while (recE != null) {
                NodoEquipoenGrupo recEQ = recE.getEquipoGrupo();
                while (recEQ != null) {
                    mensaje +=recEQ.getNombre()+" "+recEQ.getPts()+"\n";
                    recEQ = recEQ.getSiguienteEquipo();
                }
                recE = recE.getSiguienteEquipos();

            }
            recorridoG = recorridoG.getSiguienteGrupo();
            txtGrupos.setText(mensaje);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerCalendario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGrupos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCalendarioGrupo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVerCalendario.setText("Ver Calendario");
        btnVerCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCalendarioActionPerformed(evt);
            }
        });

        txtGrupos.setColumns(20);
        txtGrupos.setRows(5);
        jScrollPane1.setViewportView(txtGrupos);

        txtCalendarioGrupo.setColumns(20);
        txtCalendarioGrupo.setRows(5);
        jScrollPane2.setViewportView(txtCalendarioGrupo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnVerCalendario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVerCalendario)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCalendarioActionPerformed
        // TODO add your handling code here:
        if (estado) {
            this.setSize(500, 620);
            estado = false;
            btnVerCalendario.setText("Ocultar Calendario");
        } else {
            this.setSize(400, 420);
            estado = true;
            btnVerCalendario.setText("Ver Calendario");
        }
    }//GEN-LAST:event_btnVerCalendarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGrupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerCalendario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCalendarioGrupo;
    private javax.swing.JTextArea txtGrupos;
    // End of variables declaration//GEN-END:variables
}
