/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Listas.Equipos;
import Listas.Partidos;
import Nodos.NodoEquipo;
import Nodos.NodoJugador;
import Nodos.NodoPartidos;
import javax.swing.JPanel;
import project2014.clsLlenar;
import project2014.clsLlenarCalendario;

/**
 *
 * @author familia
 */
public class frmSedes extends javax.swing.JFrame {

    /**
     * Creates new form frmSedes
     */
    public frmSedes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtClima = new javax.swing.JTextPane();
        btnPartidos = new javax.swing.JButton();
        rbCastelao = new javax.swing.JRadioButton();
        rbPernambuco = new javax.swing.JRadioButton();
        rbPantanal = new javax.swing.JRadioButton();
        rbBaxaida = new javax.swing.JRadioButton();
        rbBeira = new javax.swing.JRadioButton();
        rbAmazonia = new javax.swing.JRadioButton();
        rbCorinthians = new javax.swing.JRadioButton();
        rbFonteNova = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        rbDasDunas = new javax.swing.JRadioButton();
        rbMineirao = new javax.swing.JRadioButton();
        rbNacional = new javax.swing.JRadioButton();
        rbMaracana = new javax.swing.JRadioButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("jRadioButtonMenuItem4");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("jRadioButtonMenuItem5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estadios");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Partidos en este estadio" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtClima);

        btnPartidos.setText("CARGAR PARTIDOS");
        btnPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidosActionPerformed(evt);
            }
        });

        rbCastelao.setText("ESTADIO CASTELAO");

        rbPernambuco.setText("ARENA PERNAMBUCO");

        rbPantanal.setText("ARENA PANTANAL");

        rbBaxaida.setText("ARENA DA BAXAIDA");
        rbBaxaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBaxaidaActionPerformed(evt);
            }
        });

        rbBeira.setText("ESTADIO BEIRA-RIO");

        rbAmazonia.setText("ARENA AMAZONIA");

        rbCorinthians.setText("ARENA CORINTHIANS");

        rbFonteNova.setText("ARENA FONTE NOVA");

        jRadioButton9.setText("ARENA AMAZONIA");

        rbDasDunas.setText("ESTADIO DAS DUNAS");

        rbMineirao.setText("ESTADIO MINEIRAO");

        rbNacional.setText("ESTADIO NACIONAL");

        rbMaracana.setText("ESTADIO MARACANA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCorinthians)
                            .addComponent(rbBaxaida)
                            .addComponent(rbFonteNova)
                            .addComponent(rbPantanal)
                            .addComponent(rbPernambuco))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbDasDunas)
                            .addComponent(rbMineirao)
                            .addComponent(rbNacional)
                            .addComponent(rbMaracana)
                            .addComponent(rbCastelao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton9)
                                    .addComponent(rbAmazonia))
                                .addGap(78, 78, 78)
                                .addComponent(rbBeira))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(btnPartidos)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbAmazonia)
                                        .addComponent(rbBeira))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCorinthians)
                            .addComponent(rbCastelao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBaxaida)
                            .addComponent(rbDasDunas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFonteNova)
                            .addComponent(rbMineirao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbPantanal)
                            .addComponent(rbNacional))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbPernambuco)
                            .addComponent(rbMaracana)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(btnPartidos)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        frmSedes estadios = new frmSedes();
        estadios.setVisible(true);
        JPanel miPanel = new JPanel();
        

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        Partidos calendar = new Partidos();
        clsLlenarCalendario cal = new clsLlenarCalendario();
        cal.Llenarcalendario(calendar);
        
        NodoPartidos recP = calendar.getCalendario();
        String clima = "";
        while (recP != null) {
            if (jComboBox1.getSelectedItem() == (recP.getLocal() + "-" + recP.getVisita())) {
                clima = ("Temperatura   " + recP.getTemperatura() + " °C" + "\n"
                        + "Viento   " + recP.getViento() + " m/s" + "\n"
                        + "Humedad   " + recP.getHumedad() + "%");
            }
            txtClima.setText(clima);
            recP= recP.getSiguientePartido();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void rbBaxaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBaxaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBaxaidaActionPerformed

    private void btnPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidosActionPerformed
        Partidos calendar = new Partidos();
        clsLlenarCalendario cal = new clsLlenarCalendario();
        cal.Llenarcalendario(calendar);
        
        NodoPartidos recP = calendar.getCalendario();
        String todosPartidos = "";
        while (recP != null) {
            
            if (rbAmazonia.isSelected() && recP.getSede() == "ARENA AMAZONIA") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbCorinthians.isSelected() && recP.getSede() == "ARENA CORINTHIANS") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbBaxaida.isSelected() && recP.getSede() == "ARENA DA BAXAIDA") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbFonteNova.isSelected() && recP.getSede() == "ARENA FONTE NOVA") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbPantanal.isSelected() && recP.getSede() == "ARENA PANTANAL") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbPernambuco.isSelected() && recP.getSede() == "ARENA PERNAMBUCO") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbBeira.isSelected() && recP.getSede() == "ESTADIO BEIRA-RIO") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbCastelao.isSelected() && recP.getSede() == "ESTADIO CASTELAO") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbDasDunas.isSelected() && recP.getSede() == "ESTADIO DAS DUNAS") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbMineirao.isSelected() && recP.getSede() == "ESTADIO MINEIRAO") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbNacional.isSelected() && recP.getSede() == "ESTADIO NACIONAL") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            if (rbMaracana.isSelected() && recP.getSede() == "ESTADIO MARACANA") {
                jComboBox1.addItem((recP.getLocal() + "-" + recP.getVisita()));
            }
            recP = recP.getSiguientePartido();
        }
        

    }//GEN-LAST:event_btnPartidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSedes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSedes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSedes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSedes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSedes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPartidos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbAmazonia;
    private javax.swing.JRadioButton rbBaxaida;
    private javax.swing.JRadioButton rbBeira;
    private javax.swing.JRadioButton rbCastelao;
    private javax.swing.JRadioButton rbCorinthians;
    private javax.swing.JRadioButton rbDasDunas;
    private javax.swing.JRadioButton rbFonteNova;
    private javax.swing.JRadioButton rbMaracana;
    private javax.swing.JRadioButton rbMineirao;
    private javax.swing.JRadioButton rbNacional;
    private javax.swing.JRadioButton rbPantanal;
    private javax.swing.JRadioButton rbPernambuco;
    private javax.swing.JTextPane txtClima;
    // End of variables declaration//GEN-END:variables
}
